/**
 * Dados dos produtos Kore Nexus
 * Cada produto tem um slug unico para SEO e indexacao no Google
 */

import {
  Pencil,
  FileSpreadsheet,
  Cpu,
  Brain,
  MessageCircle,
  Link2,
  Mail,
  BarChart3,
  LinkIcon,
  Video,
  CreditCard,
  Wallet,
  UtensilsCrossed,
  Key,
  Calculator,
  TrendingUp,
  Play,
  FileUp,
  Scissors,
  Download,
  FileText,
  IdCard,
  QrCode,
  Calendar,
  GraduationCap,
  Briefcase,
  type LucideIcon,
} from "lucide-react"

export interface Product {
  name: string
  slug: string
  description: string
  longDescription: string
  url: string
  icon: LucideIcon
  tag: string
  category: string
  categorySlug: string
  featured?: boolean
  keywords: string[]
}

export const categories = [
  { id: "produtividade", label: "Produtividade", icon: Pencil, slug: "produtividade-engenharia" },
  { id: "comunicacao", label: "Comunicacao & IA", icon: MessageCircle, slug: "comunicacao-marketing-ia" },
  { id: "automacao", label: "Automacao Comercial", icon: CreditCard, slug: "automacao-comercial-financas" },
  { id: "utilitarios", label: "Utilitarios Web", icon: LinkIcon, slug: "utilitarios-web-conteudo" },
]

export const products: Product[] = [
  // PRODUTIVIDADE E ENGENHARIA
  {
    name: "KCad",
    slug: "kcad-cad-online",
    description: "Software CAD de alta performance integrado ao navegador. Projete, edite e visualize desenhos tecnicos sem instalacao.",
    longDescription: "O KCad e a solucao definitiva para profissionais de engenharia, arquitetura e design que precisam de um software CAD potente diretamente no navegador. Com recursos avancados de edicao vetorial, layers, cotas automaticas e exportacao em multiplos formatos (DWG, DXF, PDF), voce trabalha de qualquer lugar sem necessidade de instalacao. Ideal para empresas de Jundiai e regiao que buscam produtividade e mobilidade.",
    url: "https://korecad.lovable.app/",
    icon: Pencil,
    tag: "CAD Web",
    category: "Produtividade e Engenharia",
    categorySlug: "produtividade",
    keywords: ["cad online", "autocad web", "software cad gratuito", "desenho tecnico online", "cad navegador", "software engenharia"],
  },
  {
    name: "KSheets",
    slug: "ksheets-planilhas-online",
    description: "Planilhas online para gestao robusta de dados. Formulas avancadas, graficos dinamicos e colaboracao em tempo real.",
    longDescription: "O KSheets oferece todas as funcionalidades que voce precisa para gerenciar dados empresariais com eficiencia. Com formulas avancadas, tabelas dinamicas, graficos interativos e colaboracao em tempo real, sua equipe trabalha de forma integrada. Perfeito para controle financeiro, gestao de estoques, relatorios gerenciais e analise de dados. Desenvolvido para empresas de Jundiai, Campinas e regiao.",
    url: "https://excelonlinekorenexus.lovable.app/",
    icon: FileSpreadsheet,
    tag: "Planilhas",
    category: "Produtividade e Engenharia",
    categorySlug: "produtividade",
    keywords: ["planilha online", "excel online", "planilha gratuita", "gestao dados", "planilha colaborativa", "software planilhas"],
  },
  {
    name: "Circuit Nexus Forge",
    slug: "circuit-nexus-forge-simulador-circuitos",
    description: "Aplicativo avancado para simulacao e teste de placas de circuito. Design eletronico profissional na nuvem.",
    longDescription: "O Circuit Nexus Forge e a ferramenta ideal para engenheiros eletronicos, estudantes e makers que precisam projetar e simular circuitos eletronicos. Com biblioteca completa de componentes, simulacao em tempo real, analise de sinais e exportacao para fabricacao de PCBs. Uma solucao completa para desenvolvimento de hardware em Jundiai e regiao.",
    url: "https://circuit-nexus-forge.lovable.app/",
    icon: Cpu,
    tag: "Eletronica",
    category: "Produtividade e Engenharia",
    categorySlug: "produtividade",
    keywords: ["simulador circuitos", "design pcb", "eletronica online", "simulacao circuitos", "software eletronica", "prototipagem eletronica"],
  },

  // COMUNICACAO, MARKETING E IA
  {
    name: "K-Flow Nexus",
    slug: "k-flow-nexus-api-inteligencia-artificial",
    description: "Nossa API proprietaria de Inteligencia Artificial e fluxo de dados. O cerebro que conecta todo o ecossistema Kore Nexus.",
    longDescription: "O K-Flow Nexus e o coracao tecnologico do ecossistema Kore Nexus. Uma API de inteligencia artificial avancada que processa linguagem natural, automatiza decisoes, integra sistemas e otimiza fluxos de trabalho. Ideal para empresas de Jundiai e regiao que desejam implementar IA em seus processos sem complexidade. Integracao facil com qualquer sistema existente.",
    url: "https://k-flow-nexus.lovable.app/",
    icon: Brain,
    tag: "API IA",
    category: "Comunicacao, Marketing e IA",
    categorySlug: "comunicacao",
    featured: true,
    keywords: ["api inteligencia artificial", "ia para empresas", "automacao ia", "chatbot empresarial", "processamento linguagem natural", "ia jundiai"],
  },
  {
    name: "KZap",
    slug: "kzap-mensageria-empresarial",
    description: "Plataforma de mensageria empresarial para comunicacao agil e integrada. Mensagens instantaneas corporativas com seguranca.",
    longDescription: "O KZap e a solucao de mensageria empresarial que sua empresa precisa. Comunicacao instantanea, grupos corporativos, compartilhamento de arquivos, chamadas de voz e video, tudo em um ambiente seguro e controlado. Ideal para equipes de Jundiai, Campinas e regiao que precisam de comunicacao eficiente sem depender de apps pessoais.",
    url: "https://koremsm.lovable.app/",
    icon: MessageCircle,
    tag: "Mensageria",
    category: "Comunicacao, Marketing e IA",
    categorySlug: "comunicacao",
    keywords: ["mensageria empresarial", "chat corporativo", "comunicacao empresas", "app mensagens empresa", "chat seguro empresarial"],
  },
  {
    name: "ZapKlink",
    slug: "zapklink-gerador-link-whatsapp",
    description: "Gerador profissional de Links direcionados para WhatsApp. Crie links rastreaveis e otimizados para conversao.",
    longDescription: "O ZapKlink transforma seu WhatsApp em uma maquina de vendas. Crie links personalizados com mensagens pre-definidas, rastreie cliques e conversoes, integre com campanhas de marketing e aumente suas vendas. Ferramenta essencial para negocios de Jundiai e regiao que usam WhatsApp como canal de vendas.",
    url: "https://gerarlinkzap.lovable.app/",
    icon: Link2,
    tag: "Conversao",
    category: "Comunicacao, Marketing e IA",
    categorySlug: "comunicacao",
    keywords: ["link whatsapp", "gerador link zap", "link api whatsapp", "whatsapp marketing", "link rastreavel whatsapp"],
  },
  {
    name: "KCold",
    slug: "kcold-email-marketing-automacao",
    description: "Sistema avancado para automacao e disparos de Cold Mail e Email Marketing. Sequencias inteligentes e analytics detalhado.",
    longDescription: "O KCold e sua plataforma completa de email marketing e cold outreach. Crie sequencias automatizadas, personalize mensagens em escala, acompanhe metricas de abertura e cliques, e converta mais leads em clientes. Desenvolvido para equipes de vendas e marketing de empresas de Jundiai, Campinas e SP.",
    url: "https://nexus-mail-bliss.lovable.app/",
    icon: Mail,
    tag: "Email Marketing",
    category: "Comunicacao, Marketing e IA",
    categorySlug: "comunicacao",
    keywords: ["email marketing", "cold mail", "automacao email", "disparador email", "email empresarial", "marketing digital jundiai"],
  },
  {
    name: "KAds",
    slug: "kads-gestao-trafego-pago",
    description: "Plataforma para simulacao, gestao de trafego pago e campanhas publicitarias. Domine a midia paga com precisao.",
    longDescription: "O KAds e a ferramenta que voce precisa para dominar o trafego pago. Simule campanhas, calcule ROI, gerencie orcamentos e otimize seus anuncios com dados em tempo real. Ideal para gestores de trafego, agencias e empresas de Jundiai e regiao que investem em publicidade digital.",
    url: "https://adskore.lovable.app/",
    icon: BarChart3,
    tag: "Trafego Pago",
    category: "Comunicacao, Marketing e IA",
    categorySlug: "comunicacao",
    keywords: ["gestao trafego pago", "ads manager", "google ads", "facebook ads", "midia paga", "marketing digital campinas"],
  },
  {
    name: "KBio",
    slug: "kbio-link-na-bio",
    description: "Link na Bio unificado e estilizado para redes sociais. Centralize todos os seus links com design profissional.",
    longDescription: "O KBio transforma sua bio em uma landing page poderosa. Centralize links de redes sociais, loja, contato e conteudos em uma unica pagina personalizada. Analytics integrado, temas profissionais e integracao com pixels de rastreamento. Essencial para influenciadores e empresas de Jundiai e regiao.",
    url: "https://linknabiokn.lovable.app/",
    icon: LinkIcon,
    tag: "Social Media",
    category: "Comunicacao, Marketing e IA",
    categorySlug: "comunicacao",
    keywords: ["link na bio", "linktree alternativa", "bio instagram", "centralizador links", "pagina bio"],
  },
  {
    name: "KLive",
    slug: "klive-videochat-comunicacao",
    description: "Chat em tempo real e comunicacao por video. Conecte pessoas de forma segura e instantanea com qualidade HD.",
    longDescription: "O KLive oferece comunicacao por video em tempo real com qualidade profissional. Ideal para reunioes remotas, atendimento ao cliente, consultorias online e networking. Sem instalacao, direto no navegador, com salas privadas e moderacao. Perfeito para empresas de Jundiai e regiao que precisam de comunicacao visual.",
    url: "https://omeaglechat.lovable.app/",
    icon: Video,
    tag: "Video Chat",
    category: "Comunicacao, Marketing e IA",
    categorySlug: "comunicacao",
    keywords: ["videochat", "video chamada", "reuniao online", "comunicacao video", "videoconferencia"],
  },

  // AUTOMACAO COMERCIAL E FINANCAS
  {
    name: "KCard",
    slug: "kcard-comanda-cartao-pdv",
    description: "Sistema de comanda por cartao com Gateway de Pagamento Integrado. Controle total do consumo em tempo real.",
    longDescription: "O KCard revoluciona o atendimento do seu estabelecimento. Sistema de comanda por cartao com controle de consumo em tempo real, gateway de pagamento integrado, relatorios gerenciais e gestao de mesas. Ideal para bares, restaurantes, casas noturnas e eventos em Jundiai e regiao.",
    url: "https://saldocertokn.lovable.app/",
    icon: CreditCard,
    tag: "PDV",
    category: "Automacao Comercial e Financas",
    categorySlug: "automacao",
    keywords: ["sistema comanda", "pdv restaurante", "comanda eletronica", "sistema bar", "gestao consumo", "pdv jundiai"],
  },
  {
    name: "KPay",
    slug: "kpay-gateway-pagamento",
    description: "Gateway de pagamento seguro, estavel e de alta velocidade. PIX, cartao e boleto em uma unica API.",
    longDescription: "O KPay e o gateway de pagamento que sua empresa precisa. Processe PIX instantaneo, cartoes de credito e debito, e boletos em uma unica integracao. Taxas competitivas, antifraude integrado, split de pagamentos e dashboard completo. Desenvolvido para empresas de Jundiai, Campinas e todo Brasil.",
    url: "https://gatewaypag.lovable.app/",
    icon: Wallet,
    tag: "Pagamentos",
    category: "Automacao Comercial e Financas",
    categorySlug: "automacao",
    featured: true,
    keywords: ["gateway pagamento", "processador pagamento", "api pix", "pagamento online", "integracao pagamento", "fintech jundiai"],
  },
  {
    name: "KMesa",
    slug: "kmesa-sistema-comanda-restaurante",
    description: "Sistema inteligente de comanda por mesa para restaurantes e bares. Gestao completa do atendimento.",
    longDescription: "O KMesa e o sistema de gestao para restaurantes mais completo do mercado. Comanda por mesa, cardapio digital, integracao com cozinha, controle de estoque e relatorios de vendas. Aumente a eficiencia do seu atendimento e reduza erros. Ideal para restaurantes de Jundiai, Campinas e regiao.",
    url: "https://comanda-magica-calc.lovable.app/",
    icon: UtensilsCrossed,
    tag: "Food Service",
    category: "Automacao Comercial e Financas",
    categorySlug: "automacao",
    keywords: ["sistema restaurante", "comanda mesa", "pdv restaurante", "gestao restaurante", "cardapio digital", "sistema food service"],
  },
  {
    name: "Sector Key Pal",
    slug: "sector-key-pal-controle-chaves-acesso",
    description: "Sistema automatizado de controle de chaves, portaria e acessos. Seguranca patrimonial inteligente.",
    longDescription: "O Sector Key Pal e a solucao completa para controle de chaves e acessos. Registre emprestimos de chaves, controle horarios, gere relatorios de auditoria e integre com sistemas de portaria. Ideal para condominios, empresas e industrias de Jundiai e regiao que precisam de seguranca patrimonial.",
    url: "https://sector-key-pal.lovable.app/",
    icon: Key,
    tag: "Controle de Acesso",
    category: "Automacao Comercial e Financas",
    categorySlug: "automacao",
    keywords: ["controle chaves", "sistema portaria", "controle acesso", "seguranca patrimonial", "gestao chaves", "portaria eletronica"],
  },
  {
    name: "KHelp",
    slug: "khelp-calculadora-financeira-empresarial",
    description: "Calculadora financeira empresarial para custos de terceirizacao e contratacao de sistemas.",
    longDescription: "O KHelp ajuda sua empresa a tomar decisoes financeiras inteligentes. Calcule custos de terceirizacao vs contratacao, simule cenarios de investimento em tecnologia, compare fornecedores e otimize seu orcamento de TI. Ferramenta essencial para gestores de empresas de Jundiai e regiao.",
    url: "https://calculadorafinacasempresa.lovable.app/",
    icon: Calculator,
    tag: "Financas",
    category: "Automacao Comercial e Financas",
    categorySlug: "automacao",
    keywords: ["calculadora financeira", "custo terceirizacao", "calculadora empresarial", "orcamento ti", "custo contratacao"],
  },
  {
    name: "KRoi",
    slug: "kroi-calculadora-roi-investimentos",
    description: "Calculadora avancada de Retorno Sobre Investimento (ROI) para novos negocios. Tome decisoes baseadas em dados.",
    longDescription: "O KRoi e sua ferramenta para analise de investimentos. Calcule ROI, payback, VPL e TIR de qualquer projeto ou investimento. Simule cenarios, compare alternativas e tome decisoes embasadas em dados. Ideal para empreendedores e investidores de Jundiai, Campinas e regiao.",
    url: "https://calcularinvestimento.lovable.app/",
    icon: TrendingUp,
    tag: "Investimentos",
    category: "Automacao Comercial e Financas",
    categorySlug: "automacao",
    keywords: ["calculadora roi", "retorno investimento", "analise investimento", "calculadora payback", "viabilidade projeto"],
  },

  // UTILITARIOS WEB E CONTEUDO
  {
    name: "KPlay",
    slug: "kplay-streaming-video",
    description: "Plataforma de streaming sem anuncios, otimizada para abrir ate em redes Wi-Fi com restricoes.",
    longDescription: "O KPlay oferece uma experiencia de streaming limpa e sem interrupcoes. Assista videos sem anuncios, com carregamento rapido mesmo em conexoes limitadas. Ideal para uso corporativo, escolas e ambientes com restricoes de rede em Jundiai e regiao.",
    url: "https://knvd.lovable.app/",
    icon: Play,
    tag: "Streaming",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    featured: true,
    keywords: ["streaming video", "assistir videos", "player video", "video sem anuncios", "streaming corporativo"],
  },
  {
    name: "KTemp",
    slug: "ktemp-transferencia-arquivos-temporarios",
    description: "Transferencia de arquivos temporarios seguros com link de autodestruicao. Compartilhe com confianca.",
    longDescription: "O KTemp e a forma mais segura de compartilhar arquivos sensiveis. Faca upload, defina tempo de expiracao e compartilhe com link de autodestruicao. Criptografia de ponta a ponta, sem rastros, perfeito para documentos confidenciais. Ideal para empresas de Jundiai e regiao.",
    url: "https://arquivotemp.lovable.app/",
    icon: FileUp,
    tag: "Transferencia",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["transferencia arquivos", "enviar arquivos grandes", "compartilhar arquivos", "arquivo temporario", "link autodestruicao"],
  },
  {
    name: "KLink",
    slug: "klink-encurtador-links-analytics",
    description: "Encurtador de links inteligente com foco em rastreamento e analytics. URLs curtas com insights poderosos.",
    longDescription: "O KLink transforma URLs longas em links curtos e rastreaveis. Acompanhe cliques em tempo real, analise origem do trafego, crie links personalizados e integre com suas campanhas de marketing. Essencial para profissionais de marketing de Jundiai e regiao.",
    url: "https://encurtadorlink.lovable.app/",
    icon: Scissors,
    tag: "URL Shortener",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["encurtador link", "link curto", "url shortener", "rastreamento links", "analytics links"],
  },
  {
    name: "KTok",
    slug: "ktok-download-videos-tiktok",
    description: "Plataforma rapida para baixar videos do TikTok limpos, sem marca d agua. Download instantaneo.",
    longDescription: "O KTok permite baixar videos do TikTok em alta qualidade e sem marca d agua. Simples, rapido e gratuito. Ideal para criadores de conteudo, agencias e profissionais de marketing de Jundiai e regiao que precisam reutilizar conteudo.",
    url: "https://baixartiktok.lovable.app/",
    icon: Download,
    tag: "Download",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["baixar tiktok", "download tiktok", "video sem marca dagua", "salvar tiktok", "tiktok download"],
  },
  {
    name: "KEmprego",
    slug: "kemprego-gerador-curriculo-profissional",
    description: "Gerador automatico de curriculos profissionais otimizados e gratuitos. Destaque-se no mercado de trabalho.",
    longDescription: "O KEmprego ajuda voce a criar o curriculo perfeito. Templates profissionais, dicas de preenchimento, otimizacao para sistemas ATS e exportacao em PDF. Aumente suas chances de conseguir a vaga dos sonhos. Gratuito para candidatos de Jundiai, Campinas e regiao.",
    url: "https://geradorcurriculogratis.lovable.app/",
    icon: FileText,
    tag: "Carreira",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["gerador curriculo", "curriculo gratuito", "criar curriculo", "modelo curriculo", "curriculo profissional"],
  },
  {
    name: "Gerador de Cartao de Visita",
    slug: "gerador-cartao-visita-online",
    description: "Criacao instantanea de identidade visual corporativa. Design profissional em segundos.",
    longDescription: "Crie cartoes de visita profissionais em minutos. Escolha entre dezenas de templates, personalize cores, fontes e logo, e exporte em alta resolucao para impressao ou uso digital. Ideal para profissionais e empresas de Jundiai e regiao.",
    url: "https://geradordecartaodevisitas.lovable.app/",
    icon: IdCard,
    tag: "Design",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["cartao de visita", "criar cartao visita", "design cartao", "identidade visual", "cartao profissional"],
  },
  {
    name: "KCode",
    slug: "kcode-gerador-qrcode-personalizado",
    description: "Gerador dinamico de QR Codes customizaveis. Cores, logos e formatos personalizados.",
    longDescription: "O KCode gera QR Codes profissionais e personalizados. Adicione seu logo, escolha cores, defina tamanho e formato. Ideal para campanhas de marketing, cardapios digitais, pagamentos e muito mais. Ferramenta essencial para negocios de Jundiai e regiao.",
    url: "https://gerarqrcodej.lovable.app/",
    icon: QrCode,
    tag: "QR Code",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["gerador qr code", "criar qr code", "qr code personalizado", "qr code logo", "qr code pix"],
  },
  {
    name: "KAgenda",
    slug: "kagenda-agendamento-online",
    description: "Sistema inteligente de agendamento online para marcacao de horarios. Agendamento simplificado para seu negocio.",
    longDescription: "O KAgenda e o sistema de agendamento que seu negocio precisa. Seus clientes agendam online 24/7, voce recebe notificacoes e gerencia sua agenda de qualquer lugar. Ideal para clinicas, saloes, consultorios e prestadores de servico de Jundiai e regiao.",
    url: "https://kagenda.lovable.app/",
    icon: Calendar,
    tag: "Agendamento",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["agendamento online", "sistema agendamento", "marcar horario", "agenda online", "sistema reservas"],
  },
  {
    name: "K_Cursos",
    slug: "kcursos-plataforma-cursos-online",
    description: "Plataforma completa para hospedagem de infoprodutos e cursos online. Venda conhecimento com facilidade.",
    longDescription: "O K_Cursos e sua plataforma completa para vender cursos e infoprodutos. Hospede videos, materiais, provas, certificados e gerencie alunos em um so lugar. Integrado com gateways de pagamento e ferramentas de marketing. Ideal para infoprodutores de Jundiai e regiao.",
    url: "https://learn-bright-certify.lovable.app/",
    icon: GraduationCap,
    tag: "Infoprodutos",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["plataforma cursos", "vender cursos online", "ead", "infoprodutos", "hotmart alternativa", "plataforma ead"],
  },
  {
    name: "Trabalhe Conosco",
    slug: "trabalhe-conosco-kore-nexus",
    description: "Canal direto de recrutamento e banco de talentos da Kore Nexus. Junte-se a revolucao tecnologica.",
    longDescription: "Faca parte do time Kore Nexus! Cadastre seu curriculo em nosso banco de talentos e seja notificado sobre vagas na area de tecnologia. Buscamos desenvolvedores, designers, gestores e profissionais de diversas areas em Jundiai e regiao.",
    url: "https://trabalheconoscokn.lovable.app/",
    icon: Briefcase,
    tag: "Carreiras",
    category: "Utilitarios Web e Conteudo",
    categorySlug: "utilitarios",
    keywords: ["vagas tecnologia", "trabalhe conosco", "emprego jundiai", "vaga desenvolvedor", "carreira tecnologia"],
  },
]

export const productsByCategory = {
  produtividade: products.filter((p) => p.categorySlug === "produtividade"),
  comunicacao: products.filter((p) => p.categorySlug === "comunicacao"),
  automacao: products.filter((p) => p.categorySlug === "automacao"),
  utilitarios: products.filter((p) => p.categorySlug === "utilitarios"),
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getAllProductSlugs(): string[] {
  return products.map((p) => p.slug)
}
